Reformat section "Alternatives to Rstudio"
alexd106/Rbook pull request #3
Opened 2021-03-30 10:41 UTC by frederic-santos

I propose various changes for this section:

- Add Emacs+ESS, Nvim-R and RKWard as alternatives to Rstudio
- Each alternative has now its own URL
- Alternatives are now listed by type (either text editor or advanced IDE) rather than operating system, which avoids duplicates

2021-03-30 20:48 UTC, alexd106 commented
Thanks for taking the time to propose these changes Frederic. They look very sensible to me and I'll merge your changes and acknowledge your contribution in the book.

2021-03-30 21:02 UTC, alexd106 commented
I would suggest changing:
_'A light yet efficient way to write R scripts consists in using advanced text editors such as:'_ to _'A light yet efficient way to write your R scripts using advanced text editors such as:'_

and 

_'Those environments are more powerful than simple text editors, and are similar to Rstudio:'_ to _'**These** environments are more powerful than simple text editors, and are similar to **RStudio**:'_

2021-03-30 21:14 UTC, alexd106 requested changes

2021-03-30 21:14 UTC, alexd106 commented on 01-intro.Rmd
> +A light yet efficient way to write R scripts consists in using advanced text editors such as:
I would suggest changing to: 'A light yet efficient way to write your R scripts using advanced text editors such as:'

2021-03-30 21:14 UTC, alexd106 commented on 01-intro.Rmd
> +Those environments are more powerful than simple text editors, and are similar to Rstudio:
suggest changing to 'These environments are more powerful than simple text editors, and are similar to RStudio:'

2021-03-31 06:28 UTC, frederic-santos commented
Thanks, I added your changes in my commit 77a376e.
(And many thanks for your whole book, which is the best online resource I know for beginners!)

2021-03-31 07:45 UTC, merged